name = "NeurobloxRegistry"
uuid = "b1d64cd1-75fe-41af-8099-45600c0e3392"
repo = "git@github.com:Neuroblox/NeurobloxRegistry.git"
description = "The registry for Neuroblox.jl and Neuroblox.jl related packages"

[packages]
769b91e5-4c60-41ee-bfae-153c84203cb2 = { name = "Neuroblox", path = "N/Neuroblox" }
c1a47a78-a13f-4f42-9de5-c5b922306e53 = { name = "NeurobloxBase", path = "N/NeurobloxBase" }
